"""dell column  cell_phones

Revision ID: 39561f35e023
Revises: c3f5ee51d614
Create Date: 2022-12-22 22:39:36.210592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39561f35e023'
down_revision = 'c3f5ee51d614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'cell_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('cell_phone', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
