"""change name column

Revision ID: 645bb9be7001
Revises: 215310b0e565
Create Date: 2022-12-21 02:44:53.025351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645bb9be7001'
down_revision = '215310b0e565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('contacts', 'start_work')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('start_work', sa.DATE(), nullable=True))
    op.drop_column('contacts', 'birthday')
    # ### end Alembic commands ###
