"""add table phones

Revision ID: 8c6ee04a1d6f
Revises: 39561f35e023
Create Date: 2022-12-24 00:45:06.786353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6ee04a1d6f'
down_revision = '39561f35e023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
