"""edit models for delete cascade

Revision ID: a058a5b840f9
Revises: bb5cd655deb7
Create Date: 2022-12-28 23:08:16.858541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a058a5b840f9'
down_revision = 'bb5cd655deb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
